# Generated by Django 3.1.4 on 2021-01-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblFeederPillars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=25, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.FloatField(blank=True, max_length=50, null=True)),
                ('incomingct', models.FloatField(blank=True, max_length=50, null=True)),
                ('outgoingct', models.FloatField(blank=True, max_length=50, null=True)),
                ('ipaddr', models.CharField(blank=True, max_length=50, null=True)),
                ('macaddr', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblFeederPillars',
                'managed': False,
            },
        ),
    ]
