# Generated by Django 3.1.4 on 2021-03-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tblfeederpillars'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblfpsummary',
            fields=[
                ('rowid', models.AutoField(primary_key=True, serialize=False)),
                ('fpsn', models.CharField(max_length=50)),
                ('fpstatus', models.CharField(max_length=50)),
                ('fpipaddr', models.CharField(max_length=50)),
                ('fplocation', models.CharField(max_length=50)),
                ('fprating', models.CharField(max_length=50)),
                ('fpremarks', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tblfpsummary',
                'managed': False,
            },
        ),
    ]
